included: # paths to include during linting. `--path` is ignored if present.
  - FSNotesCore
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length:
  warning: 220

disabled_rules: 
  - implicit_getter
  - identifier_name

cyclomatic_complexity: 20
function_body_length: 100
file_length: 1000
